build_root: .paradev/.cache/build
supported_version: 1.19.*
picture: thumbnail.png
remote_file_id: "3154495198"
tags:
  - Alternative History
  - Gameplay
  - Map
  - Technologies
  - Sound
  - National Focuses
  - Events
  - Ideologies
replace_path:
  - common/abilities
  - common/aces
  - common/achievements
  - common/ai_equipment
  - common/ai_equipments
  - common/ai_faction_theaters
  - common/ai_focuses
  - common/ai_navy
  - common/ai_navy/fleet
  - common/ai_navy/goals
  - common/ai_navy/taskforce
  - common/ai_strategy
  - common/ai_strategy_plans
  - common/ai_templates
  - common/autonomous_states
  - common/bookmarks
  - common/bop
  - common/buildings
  - common/characters
  - common/collections
  - common/countries
  - common/country_leader
  - common/continuous_focus
  - common/country_tag_aliases
  - common/country_tags
  - common/decisions
  - common/decisions/categories
  - common/difficulty_settings
  - common/equipment_groups
  - common/factions
  - common/factions/goals
  - common/factions/icons
  - common/factions/member_upgrades
  - common/factions/member_upgrades/member_groups
  - common/factions/rules
  - common/factions/rules/groups
  - common/factions/templates
  - common/factions/upgrades
  - common/factions/upgrades/groups
  - common/focus_inlay_windows
  - common/game_rules
  - common/idea_tags
  - common/ideas
  - common/ideologies
  - common/modifiers
  - common/dynamic_modifiers
  - common/intelligence_agencies
  - common/intelligence_agency_upgrades
  - common/doctrines
  - common/doctrines/folders
  - common/doctrines/grand_doctrines
  - common/doctrines/subdoctrines
  - common/doctrines/subdoctrines/air
  - common/doctrines/subdoctrines/land
  - common/doctrines/subdoctrines/sea
  - common/doctrines/subdoctrines/special_forces
  - common/doctrines/tracks
  - common/military_industrial_organization/organizations
  - common/military_industrial_organization/ai_bonus_weights
  - common/military_industrial_organization/policies
  - common/medals
  - common/modifier_definitions
  - common/mtth
  - common/names
  - common/national_focus
  - common/occupation_laws
  - common/on_actions
  - common/operations
  - common/raids
  - common/raids/categories
  - common/resistance_compliance_modifiers
  - common/resistance_activity
  - common/resources
  - common/scorers
  - common/scripted_diplomatic_actions
  - common/scripted_effects
  - common/scripted_guis
  - common/scripted_localisation
  - common/scripted_triggers
  - common/script_constants
  - common/state_category
  - common/special_projects
  - common/special_projects/project_tags
  - common/special_projects/projects
  - common/special_projects/prototype_rewards
  - common/special_projects/specialization
  - common/technologies
  - common/technology_tags
  - common/technology_sharing
  - common/timed_activities
  - common/unit_tags
  - common/units
  - common/unit_leader
  - common/unit_medals
  - common/units/codenames_operatives
  - common/units/equipment
  - common/units/equipment/upgrades
  - common/units/names
  - common/units/names_divisions
  - common/units/names_railway_guns
  - common/units/names_ships
  - common/wargoals
  - common/operation_tokens
  - common/operation_phases
  - common/peace_conference
  - common/peace_conference/ai_peace
  - common/peace_conference/categories
  - common/peace_conference/cost_modifiers
  - country_metadata
  - dlc/dlc036_by_blood_alone/gfx/entities
  - events
  - gfx/flags
  - gfx/leaders
  - gfx/loadingscreens
  - gfx/event_pictures
  - gfx/interface/equipmentdesigner/graphic_db
  - history/countries
  - history/general
  - history/states
  - history/units
  - map
  - map/strategicregions
  - map/supplyareas
  - map/terrain
  - portraits
  - tutorial
