NDefines.NGame.START_DATE = "1002.12.1.12";
NDefines.NGame.END_DATE = "1099.12.31.12";
NDefines.NDiplomacy.TENSION_DECAY_DAILY = 0.000;
NDefines.NDiplomacy.TENSION_STATE_VALUE = 0;						                        -- Tension value gained by annexing one state
NDefines.NDiplomacy.TENSION_CIVIL_WAR_IMPACT = 0;					                        -- civil war multiplier on tension.
NDefines.NDiplomacy.TENSION_NO_CB_WAR = 0;							                        -- Amount of tension generated by a no-CB wargoal
NDefines.NDiplomacy.TENSION_CB_WAR = 0;								                        -- Amount of tension generated by a war with a CB
NDefines.NDiplomacy.TENSION_ANNEX_NO_CLAIM = 0;						                        -- Amount of tension generated by annexing a state you don't have claims on
NDefines.NDiplomacy.TENSION_ANNEX_CLAIM = 0;						                        -- Amount of tension generated by annexing a state you DO have claims on
NDefines.NDiplomacy.TENSION_ANNEX_CORE = 0;							                        -- Amount of tension generated by annexing a state that is your core
NDefines.NDiplomacy.TENSION_PUPPET = 0;							                            -- Amount of tension generated by puppeting (per state)
NDefines.NDiplomacy.TENSION_FORCE_GOVERNMENT = 0;                                           -- Amount of tension generated by forcing government (per state)
NDefines.NDiplomacy.TENSION_VOLUNTEER_FORCE_DIVISION = 0;			                        -- Amount of tension generated for each sent division
NDefines.NDiplomacy.TENSION_DECAY_DAILY = 0.000;					                        -- Each day tension decays this much for Threat sources which are no longer relevant. Replaces TENSION_DECAY as of 1.12.0
NDefines.NDiplomacy.TENSION_SIZE_FACTOR = 1.0;						                        -- All action tension values are multiplied by this value
NDefines.NDiplomacy.TENSION_TIME_SCALE_START_DATE = "1002.12.1.12";	                        -- Starting at this date, the tension values will be scaled down (will be equal to 1 before that)
NDefines.NDiplomacy.TENSION_TIME_SCALE_MONTHLY_FACTOR = 0;		                            -- Timed tension scale will be modified by this amount starting with TENSION_TIME_SCALE_START_DATE
NDefines.NDiplomacy.TENSION_TIME_SCALE_MIN = 1.0;				                            -- Timed tension scale won't decrease under this value
NDefines.NDiplomacy.TENSION_GUARANTEE = 0;
NDefines.NDiplomacy.TENSION_FACTION_JOIN = 0;
NDefines.NDiplomacy.TENSION_JOIN_ATTACKER = 0;						                        -- scale of the amount of tension added when country joins attacker side
NDefines.NDiplomacy.TENSION_PEACE_FACTOR = 0;					                            -- scale of the amount of tension (from war declaration) reduced when peace is completed.
NDefines.NDiplomacy.TENSION_LIBERATE = 0;							                        -- Amount of tension generated by liberating a country.
NDefines.NDiplomacy.TENSION_TAKE_ONE_CAPITAL_SHIP = 0;			                            -- Amount of tension generated by 1 take navy peace action
NDefines.NDiplomacy.TENSION_DEMILITARIZE_ZONE = 0;				                            -- Amount of tension generated by stacking demilitarize zone on 1 state, multiplied with the state base threat
NDefines.NDiplomacy.TENSION_WAR_REPARATION = 0;					                            -- Amount of tension generated by stacking war reparation on 1 state, multiplied with the state base threat
NDefines.NDiplomacy.TENSION_RESOURCE_RIGHTS = 0;					                        -- Amount of tension generated by stacking resource rights on 1 state, multiplied with the state base threat
NDefines.NDiplomacy.TENSION_DISMANTLE_INDUSTRY = 0;				                            -- Amount of tension generated by stacking dismantle military industry on 1 state, multiplied with the state base threat
NDefines.NDiplomacy.TENSION_CAPITULATE = 0;						                            -- Scale of the amount of tension created by a countries capitulation.
NDefines.NCountry.CIVIL_WAR_INVOLVEMENT_MIN_TENSION = 0;		                            -- base value of world tension to involve other sides to the civil war
NDefines.NCountry.LOCAL_MANPOWER_ACCESSIBLE_NON_CORE_FACTOR = 0.08;	                        -- Fraction of manpower from non-core states that is accessible
NDefines.NCountry.BASE_MOBILIZATION_SPEED = 0.03;					                        -- Base speed of manpower mobilization  #in 1/1000 of 1 %
NDefines.NTechnology.BASE_YEAR_AHEAD_PENALTY_FACTOR = 40;		                            -- Base year ahead penalty
NDefines.NTechnology.BASE_TECH_COST = 120;					                                -- Base cost for a tech. multiplied with tech cost and ahead of time penalties
NDefines.NProduction.MINIMUM_NUMBER_OF_FACTORIES_TAKEN_BY_CONSUMER_GOODS_PERCENT = 0.0;		-- The minimum number of factories we have to put on consumer goods, in percent.
NDefines.NMilitary.SLOWEST_SPEED = 0.5;
NDefines.NMilitary.FIELD_EXPERIENCE_SCALE = 0.0075;
NDefines.NMilitary.FIELD_EXPERIENCE_MAX_PER_DAY = 2.5;				                        -- Most xp you can gain per day

NDefines.NProject.BREAKTHROUGH_DAILY_TECHNOLOGY_GAIN = 48;                                  -- Amount in 1/100th percentage. E.g. 25 = 0.25%
NDefines.NProject.BREAKTHROUGH_DAILY_SCIENTIST_SKILL_GAIN = 20;                             -- Amount in 1/100th percentage gained per skill when doing basic research. E.g. 5 = 0.05% per skill level.

NDefines.NCountry.PARADROP_AIR_SUPERIORITY_RATIO = 0.4;
NDefines.NMilitary.PARADROP_HOURS = 24;
NDefines.NAir.STRATEGIC_BOMBER_NUKE_AIR_SUPERIORITY = 0.6;
NDefines.NAir.MIN_PLANE_COUNT_PARADROP = 20;
