"""Generate PIHC3 startup state variables for terrain temperature influence."""

from __future__ import annotations

import argparse
import csv
import json
import sys
from collections import Counter, defaultdict
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
DEFINITION_PATH = Path("src/modules/game_asset/GAME_ASSET_MAP_DEFINITION/map/definition.csv")
PROV2STATE_PATH = Path("src/modules/game_asset/GAME_ASSET_MAP_PROV2STATE/map/prov2state.json")
OUTPUT_PATH = Path("src/modules/scripted_effect/PIHC_STATE_TEMPERATURE_TERRAIN_VARS/def.txt")

TERRAIN_RANGES = {
    "urban": (0, 5),
    "desert": (5, 15),
    "mountain": (-10, 0),
    "hills": (-3, 0),
    "plains": (-2, 3),
}
NON_LAND_TERRAINS = frozenset({"unknown", "ocean"})


def province_terrain_map(project_root: Path = PROJECT_ROOT) -> dict[str, str]:
    """Return province id to terrain token from PIHC3's map definition source."""

    out: dict[str, str] = {}
    with (project_root / DEFINITION_PATH).open(newline="", encoding="utf-8") as handle:
        for row in csv.reader(handle, delimiter=";"):
            if len(row) >= 7:
                out[row[0]] = row[6]
    return out


def state_terrain_counts(project_root: Path = PROJECT_ROOT) -> dict[int, Counter[str]]:
    """Return terrain counts by state using the checked-in province-to-state source."""

    province_terrain = province_terrain_map(project_root)
    province_to_state = json.loads((project_root / PROV2STATE_PATH).read_text(encoding="utf-8"))
    out: dict[int, Counter[str]] = defaultdict(Counter)
    for province_id, state_id in province_to_state.items():
        terrain = province_terrain.get(province_id)
        if terrain:
            out[int(state_id)][terrain] += 1
    return dict(out)


def state_temperature_terrains(project_root: Path = PROJECT_ROOT) -> dict[int, str]:
    """Return state ids mapped to the terrain token used for temperature ranges."""

    out: dict[int, str] = {}
    for state_id, counts in sorted(state_terrain_counts(project_root).items()):
        if counts["urban"] > 0:
            out[state_id] = "urban"
            continue

        land_counts = Counter(
            {terrain: count for terrain, count in counts.items() if terrain not in NON_LAND_TERRAINS}
        )
        dominant_counts = land_counts or counts
        terrain = sorted(dominant_counts.items(), key=lambda item: (-item[1], item[0]))[0][0]
        if terrain in TERRAIN_RANGES:
            out[state_id] = terrain
    return out


def state_temperature_ranges(project_root: Path = PROJECT_ROOT) -> dict[int, tuple[int, int]]:
    """Return state ids mapped to outdoor temperature influence min/max ranges."""

    return {
        state_id: TERRAIN_RANGES[terrain]
        for state_id, terrain in state_temperature_terrains(project_root).items()
    }


def render_state_temperature_initializer(project_root: Path = PROJECT_ROOT) -> str:
    """Render the generated scripted effect that initializes state temperature terrain vars."""

    terrains = state_temperature_terrains(project_root)
    ranges = state_temperature_ranges(project_root)
    lines = [
        "# Generated by projects/PIHC3/scripts/generate_state_temperature_terrain_vars.py.",
        "# Source: map definition terrain plus province-to-state data.",
        "",
        "PIHC_initialize_state_outdoor_temperature_influence = {",
        "\tevery_state = {",
        "\t\tset_variable = {",
        "\t\t\tVAR_OUTDOOR_TEMPERATURE_INFLUENCE_MIN = 0",
        "\t\t}",
        "\t\tset_variable = {",
        "\t\t\tVAR_OUTDOOR_TEMPERATURE_INFLUENCE_MAX = 0",
        "\t\t}",
        "\t}",
    ]
    for state_id in sorted(ranges):
        minimum, maximum = ranges[state_id]
        terrain = terrains[state_id]
        lines.extend(
            [
                f"\t# {terrain}",
                f"\t{state_id} = {{",
                "\t\tset_variable = {",
                f"\t\t\tVAR_OUTDOOR_TEMPERATURE_INFLUENCE_MIN = {minimum}",
                "\t\t}",
                "\t\tset_variable = {",
                f"\t\t\tVAR_OUTDOOR_TEMPERATURE_INFLUENCE_MAX = {maximum}",
                "\t\t}",
                "\t}",
            ]
        )
    lines.append("}")
    return "\n".join(lines) + "\n"


def write_state_temperature_initializer(
    project_root: Path = PROJECT_ROOT,
    output_path: Path | None = None,
) -> Path:
    """Write the generated initializer effect and return its path."""

    destination = project_root / (output_path or OUTPUT_PATH)
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(render_state_temperature_initializer(project_root), encoding="utf-8")
    return destination


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--project-root", type=Path, default=PROJECT_ROOT)
    parser.add_argument("--output", type=Path, default=OUTPUT_PATH)
    parser.add_argument("--check", action="store_true", help="Fail if the generated file is stale.")
    args = parser.parse_args(argv)

    expected = render_state_temperature_initializer(args.project_root)
    destination = args.project_root / args.output
    if args.check:
        actual = destination.read_text(encoding="utf-8") if destination.is_file() else ""
        if actual != expected:
            print(f"Generated initializer is stale: {destination}", file=sys.stderr)
            return 1
        return 0

    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(expected, encoding="utf-8")
    print(destination)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
